language: node_js
node_js:
  - "8"
  - "9"
  - "10"
dist: trusty
addons:
  chrome: stable
before_deploy:
  - npm install
deploy:
  - provider: npm
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: Cox-Automotive/alks.js
    email: $NPM_EMAIL

