language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
dist: trusty
addons:
  chrome: stable
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: Cox-Automotive/alks.js
    node: '10'
  email: $NPM_EMAIL
  skip_cleanup: true

