name: Check For Release Tag

on:
  pull_request:
    branches: [ master ]

jobs:
  check_for_release_tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # checkout the master branch to compare CHANGELOG.md  
    - uses: actions/checkout@v2
      with:
        ref: master
        path: ./masterbranch

    - name: Verify that a release label exists on the PR
      if: ${{ ! ( contains(github.event.pull_request.labels.*.name, 'release/patch') || contains(github.event.pull_request.labels.*.name, 'release/minor') || contains(github.event.pull_request.labels.*.name, 'release/major') || contains(github.event.pull_request.labels.*.name, 'release/skip') ) }}
      run: echo "Please label your PR with a release label" && exit 1

    # ensure CHANGELOG.md has been updated in this PR by comparing it to the one in the master branch
    - name: Verify that CHANGELOG.md has been updated
      if: ${{ contains(github.event.pull_request.labels.*.name, 'release/patch') || contains(github.event.pull_request.labels.*.name, 'release/minor') || contains(github.event.pull_request.labels.*.name, 'release/major') }}
      run: |
        ! cmp --silent <(cat CHANGELOG.md) <(cat ./masterbranch/CHANGELOG.md) || { echo 'CHANGELOG.md must be updated for release PRs. Please update CHANGELOG.md' && exit 1 ; }