# This workflow automerges Dependabot PRs if they pass tests

name: Dependabot Automerge

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
  
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm test
      - name: "Merge PR"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
